version: "3.9"
services:
  backend:
    build: ./backend/
    ports: 
      - "3001:80"
    depends_on:
      - "database"
    environment:
      ASPNETCORE_URLS: "http://+80" 
      connectionStrings:default: "Server=localhost;Database=tempdb;User Id=sa;Password=prU*REXU4RU%%@;"
  frontend:
    build: ./frontend/
    ports:
      - "3000:80"
    depends_on:
      - "backend"
  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "prU*REXU4RU%%@"
